# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  scrape_timeout:      10s

  external_labels:
      region: 'us-west-2'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ecs'
    scrape_interval: 20s
    file_sd_configs:
      - files:
          # scrape tasks that are discovered every minute (default)
          - /etc/prometheus/1m-tasks.json
    relabel_configs:
      - source_labels: [metrics_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)

rule_files:
  # Recording rules
  # Alerts
  - /etc/prometheus/alerts/global.yml